name: Get SHA256

on:
  workflow_dispatch:

jobs:
  sha256:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Print SHA256 fingerprint
        run: |
          keytool -list -v \
          -keystore keystore.jks \
          -alias ${{ secrets.KEY_ALIAS }} \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          | grep SHA256
